// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package DI

import (
	"github.com/google/wire"
)

// Injectors from DIContainer.go:

func InitDIContainer() (*AppService, error) {
	appService := provideAppService()
	return appService, nil
}

// DIContainer.go:

type AppService struct{}

var (
	AppServiceSet = wire.NewSet(provideAppService)
)

func provideAppService() *AppService {
	return &AppService{}
}
