// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package DI

import (
	"WeatherAPI/UI"
	"WeatherAPI/UI/API"
	"github.com/google/wire"
)

// Injectors from DIContainer.go:

func InitDIContainer() (*AppService, error) {
	appService := provideAppService()
	return appService, nil
}

// DIContainer.go:

type AppService struct{}

var (
	controllersSet = wire.NewSet(provideControllers)
	AppServiceSet  = wire.NewSet(provideAppService, controllersSet)
)

func provideControllers(wc API.WeatherController) *UI.Controllers {
	return &UI.Controllers{
		WeatherController: wc,
	}
}

func provideAppService() *AppService {
	return &AppService{}
}
